version: 2.1

executors:
  build:
    parameters:
      go-version:
        type: string
    docker:
      - image: circleci/golang:<< parameters.go-version >>
        environment:
          GO111MODULE: "on"
    working_directory: ~/repo

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "server/go.sum" }}

      - run: cd server && go mod download
      - run: cd server && go mod tidy

      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "server/go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  build:
    parameters:
      go-version:
        type: string

    executor:
      name: build
      go-version: << parameters.go-version >>

    steps:
      - checkout

      - go_mod_download

      - run:
          name: Run Tests
          command: cd server && go test -v ./...

workflows:
  golang-workflow:
    jobs:
      - build:
          go-version: "1.11.5"
          golangci-lint-version: "1.15.0"